package javaapplication5;


import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Melvin Mathew
 */
public class samplevedi extends javax.swing.JFrame {
double firstnum;
double secondnum;
double result;
String operations;
boolean zero;
boolean dec;


        
/**
     * Creates new form samplevedi
     */
    public samplevedi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        mem = new javax.swing.JTextField();
        b9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        r = new javax.swing.JRadioButton();
        d = new javax.swing.JRadioButton();
        g = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jButton71 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        res = new javax.swing.JTextArea();
        res1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        y = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        op = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        res2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(6, 5));

        jButton1.setBackground(new java.awt.Color(255, 180, 68));
        jButton1.setText("AC");
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jButton1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);

        jButton3.setBackground(new java.awt.Color(255, 180, 68));
        jButton3.setText("M+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);

        jButton7.setBackground(new java.awt.Color(255, 180, 68));
        jButton7.setText("M-");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7);

        jButton8.setBackground(new java.awt.Color(255, 180, 68));
        jButton8.setText("MR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8);

        jButton4.setBackground(new java.awt.Color(255, 180, 68));
        jButton4.setText("±");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);

        jButton21.setBackground(new java.awt.Color(255, 180, 68));
        jButton21.setText("(");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton21);

        jButton22.setBackground(new java.awt.Color(255, 180, 68));
        jButton22.setText(")");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton22);
        jPanel4.add(mem);

        b9.setBackground(java.awt.Color.lightGray);
        b9.setText("9");
        b9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b9MouseExited(evt);
            }
        });
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel4.add(b9);

        jButton5.setBackground(java.awt.Color.lightGray);
        jButton5.setText("8");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);

        jButton11.setBackground(java.awt.Color.lightGray);
        jButton11.setText("7");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton11MouseExited(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton11);

        jButton24.setBackground(new java.awt.Color(255, 180, 68));
        jButton24.setText("*");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton24);

        jButton15.setBackground(java.awt.Color.lightGray);
        jButton15.setText("4");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton15MouseExited(evt);
            }
        });
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton15);

        jButton13.setBackground(java.awt.Color.lightGray);
        jButton13.setText("5");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton13MouseExited(evt);
            }
        });
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton13);

        jButton9.setBackground(java.awt.Color.lightGray);
        jButton9.setText("6");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton9MouseExited(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9);

        jButton6.setBackground(new java.awt.Color(255, 180, 68));
        jButton6.setText("/");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);

        jButton17.setBackground(java.awt.Color.lightGray);
        jButton17.setText("1");
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton17MouseExited(evt);
            }
        });
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton17);

        jButton18.setBackground(java.awt.Color.lightGray);
        jButton18.setText("2");
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton18MouseExited(evt);
            }
        });
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton18);

        jButton19.setBackground(java.awt.Color.lightGray);
        jButton19.setText("3");
        jButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton19MouseExited(evt);
            }
        });
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton19);

        jButton16.setBackground(new java.awt.Color(255, 180, 68));
        jButton16.setText("+");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton16);

        jButton12.setBackground(java.awt.Color.lightGray);
        jButton12.setText("0");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton12MouseExited(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12);

        jButton14.setBackground(java.awt.Color.lightGray);
        jButton14.setText(".");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton14MouseExited(evt);
            }
        });
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton14);

        jButton20.setBackground(java.awt.Color.lightGray);
        jButton20.setText("00");
        jButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton20MouseExited(evt);
            }
        });
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton20);

        jButton25.setBackground(new java.awt.Color(255, 180, 68));
        jButton25.setText("-");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton25);

        jButton26.setText("=");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 199, Short.MAX_VALUE)
                .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 44, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        buttonGroup1.add(r);
        r.setSelected(true);
        r.setText("RADIANS");

        buttonGroup1.add(d);
        d.setText("DEGREE");
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });

        buttonGroup1.add(g);
        g.setText("GRADIANS");

        jPanel5.setLayout(new java.awt.GridLayout(6, 8));

        jButton71.setText("sin");
        jButton71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton71ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton71);

        jButton65.setText("<html><sup>2</sup>√x");
        jButton65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton65ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton65);

        jButton64.setText("<html><sup>3</sup>√x");
        jButton64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton64ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton64);

        jButton63.setText("<html><sup>y</sup>√x");
        jButton63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton63ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton63);

        jButton68.setText("cos");
        jButton68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton68ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton68);

        jButton62.setText("<html>x<sup>2");
        jButton62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton62ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton62);

        jButton67.setText("<html>x<sup>3");
        jButton67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton67ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton67);

        jButton66.setText("<html>x<sup>y");
        jButton66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton66ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton66);

        jButton73.setText("tan");
        jButton73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton73ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton73);

        jButton31.setText("log");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton31);

        jButton32.setText("ant");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton32);

        jButton43.setText("∏");
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton43);

        jButton72.setText("<html>sin<sup>-1");
        jButton72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton72ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton72);

        jButton30.setText("1/x");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton30);

        jButton36.setText("x!");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton36);

        jButton75.setText("%");
        jButton75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton75ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton75);

        jButton70.setText("<html>cos<sup>-1");
        jButton70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton70ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton70);

        jButton56.setText("prod");
        jButton56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton56ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton56);

        jButton50.setText("sum");
        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton50);

        jButton74.setText("rev");
        jButton74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton74ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton74);

        jButton69.setText("<html>tan<sup>-1");
        jButton69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton69ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton69);

        jButton44.setText("Area");
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton44);

        jButton76.setText("volume");
        jButton76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton76ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton76);

        jButton77.setText("jButton9");
        jPanel5.add(jButton77);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(g, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addGap(2, 2, 2))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(g)
                    .addComponent(d)
                    .addComponent(r))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addGap(0, 29, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        res.setColumns(20);
        res.setRows(5);
        res.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                resKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(res);

        res1.setEditable(false);
        res1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton2.setText("←");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("X=");

        jLabel2.setText("RESULT");

        jLabel3.setText("Y=");

        y.setText("0");

        x.setText("0");

        jLabel4.setText("Enter No");

        op.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        op.setText("+/*-");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        res2.setColumns(20);
        res2.setRows(5);
        res2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                res2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                res2KeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(res2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(op, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(res1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addComponent(op, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(res1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(y, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(x)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        double ops=Double.parseDouble(String.valueOf(res.getText()));
        ops=ops*-1;
        
      res.setText(String.valueOf(ops));
      
        
        
        ops=0;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed


op.setText("+");
 firstnum=Double.parseDouble(res.getText());
 res.setText("");res2.setText(firstnum+"");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton64ActionPerformed
        double n=Double.parseDouble(res.getText());x.setText(n+"");
        res1.setText((Math.cbrt(n))+"");res2.setText("3√"+n);op.setText("+/*-");
    }//GEN-LAST:event_jButton64ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
res.setText("0");res1.setText("0");
x.setText("0");y.setText("0");op.setText("+/*-");
zero = false;


dec = false;res2.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
if(!zero && !dec){
    res.setText(null);
    
}zero = true;        res.append(9+"");
    }//GEN-LAST:event_b9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
res.append(8+"");if(!zero && !dec){
    res.setText(null);
    
}zero = true;
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
res.append(7+"");    if(!zero && !dec){
    res.setText(null);
    
}zero = true;    // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
res.append(4+"");      if(!zero && !dec){
    res.setText(null);
    
}zero = true;  // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
res.append(5+"");    if(!zero && !dec){
    res.setText(null);
    
}zero = true;    // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
res.append(6+"");   if(!zero && !dec){
    res.setText(null);
    
}zero = true;     // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
res.append(1+""); if(!zero && !dec){
    res.setText(null);
    
}zero = true;       // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
res.append(2+"");       if(!zero && !dec){
    res.setText(null);
    
}zero = true; // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
res.append(3+"");    if(!zero && !dec){
    res.setText(null);
    
}zero = true;    // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
if(!zero && !dec){
    res.setText(null);
    
}
        res.append(0+"");      
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
if(!dec){
    res.append(".");
    dec=true;
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed


op.setText("*"); firstnum=Double.parseDouble(res.getText());
res.setText("");
res2.setText(firstnum+"");

   // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed


op.setText("/");
 firstnum=Double.parseDouble(res.getText());

res.setText("");res2.setText(firstnum+"");
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed

        res.append("00"); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
secondnum=Double.parseDouble(res.getText());
String oper=op.getText();
res2.append(" "+oper+" "+secondnum);
if(oper=="+"){
   res1.setText(firstnum+secondnum+"");
}
else if(oper=="-"){
   res1.setText(firstnum-secondnum+"");
}
if(oper=="*"){
   res1.setText(firstnum*secondnum+"");
}
if(oper=="/"){
   res1.setText(firstnum/secondnum+"");
}
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed

    }//GEN-LAST:event_jPanel1KeyPressed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        res.setText(String.valueOf(mem.getText()));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        mem.setText("0");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        mem.setText(String.valueOf(res.getText()));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        firstnum=Double.parseDouble(res.getText());
        secondnum=1/firstnum;res2.setText("1/"+firstnum);
        res1.setText(secondnum+"");
        int n=Integer.parseInt(res.getText());
        x.setText(n+"");
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
res.setText(String.valueOf(Math.PI));   
res2.setText("");res1.setText("");
        
dec=true;
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        long n=Long.parseLong(res.getText());
        
        if(n>=1 && n<=59){
            x.setText(n+"");
       long f=1;
       for(long i=n;i>=1;i--)
            f*=i;
        res1.setText(f+"");res2.setText(n+"!");
        }
        else{res1.setText("");res2.setText("");
            JOptionPane.showMessageDialog(this,"Enter number betwwen 1 and 59" );
        }
        
       
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      String backspace="";  if(res.getText().length()>0){
            StringBuilder str=new StringBuilder(res.getText());
            str.deleteCharAt(res.getText().length()-1);
            backspace=str.toString();
            res.setText(backspace);
            
        }
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed


op.setText("-");    
 firstnum=Double.parseDouble(res.getText());res2.setText(firstnum+"");
res.setText("");


// TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
       res.append("(");
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
res.append(")");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton62ActionPerformed
       double n=Double.parseDouble(res.getText());x.setText(n+"");
        
       res1.setText((Math.pow(n,2))+"");
       res2.setText(n+"^2");op.setText("+/*-");
  
    }//GEN-LAST:event_jButton62ActionPerformed

    private void jButton67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton67ActionPerformed
        double n=Double.parseDouble(res.getText());x.setText(n+"");
        
       res1.setText((Math.pow(n,3))+"");res2.setText(n+"^3");
    }//GEN-LAST:event_jButton67ActionPerformed

    private void jButton66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton66ActionPerformed
    int y1=Integer.parseInt (JOptionPane.showInputDialog(this,"Enter value Y"));
     double n=Double.parseDouble(res.getText());x.setText(n+"");
        
       res1.setText((Math.pow(n,y1))+"");res2.setText(n+"^"+y1);
    y.setText(y1+"");op.setText("+/*-");
       
    }//GEN-LAST:event_jButton66ActionPerformed

    private void jButton65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton65ActionPerformed
        double n=Double.parseDouble(res.getText());x.setText(n+"");
        res1.setText((Math.sqrt(n))+"");
        res2.setText("2√"+n);op.setText("+/*-");
        
    }//GEN-LAST:event_jButton65ActionPerformed

    private void resKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resKeyPressed
     
    }//GEN-LAST:event_resKeyPressed

    private void resKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resKeyTyped
           char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE)||(c==KeyEvent.VK_ENTER))){
            getToolkit().beep();
            evt.consume();
            
        }
    }//GEN-LAST:event_resKeyTyped

    private void jButton63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton63ActionPerformed
 double n=Double.parseDouble(res.getText());x.setText(n+"");
  int y1=Integer.parseInt (JOptionPane.showInputDialog(this,"Enter value Y"));
        res1.setText(Math.pow(n,1.0/y1)+"");    
         y.setText(y1+"");res2.setText(y1+"√"+n);op.setText("+/*-");
    }//GEN-LAST:event_jButton63ActionPerformed

    private void res2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_res2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_res2KeyPressed

    private void res2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_res2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_res2KeyTyped

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
    long n=Long.parseLong(res.getText());long a=0,b,sum=0;
 
        while(n!=0){
            b=n%10;
            sum+=b;
            n/=10;
        }
        res2.setText("SUM");
    res1.setText(sum+"");
        
    }//GEN-LAST:event_jButton50ActionPerformed

    private void jButton56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton56ActionPerformed
    long n=Long.parseLong(res.getText());long a=0,b,prod=1;
 
        while(n!=0){
            b=n%10;
            prod*=b;
            n/=10;
        }
        res2.setText("PRODUCT");
    res1.setText(prod+"");
    }//GEN-LAST:event_jButton56ActionPerformed

    private void jButton74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton74ActionPerformed
      long n=Long.parseLong(res.getText());long a=0,b,rev=0;
 
        while(n!=0){
            b=n%10;
            rev=rev*10+b;
            n/=10;
        }
        res2.setText("REVERSE");
    res1.setText(rev+"");
    }//GEN-LAST:event_jButton74ActionPerformed

    private void jButton71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton71ActionPerformed
double n=Double.parseDouble(res.getText());
    if(r.isSelected()){
        res1.setText( Math.sin(n)+"(rad)")    ;
       res2.setText("sin("+n+")");
    }  
    else if(d.isSelected()){
res1.setText((Math.sin(n)*180/Math.PI)+"deg")    ;
       res2.setText("sin("+n+")");
    }
     else if(g.isSelected()){
res1.setText( (Math.sin(n))+"deg")    ;
       res2.setText("sin("+n+")");
    }

       
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton71ActionPerformed

    private void jButton68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton68ActionPerformed
double n=Double.parseDouble(res.getText());
       res1.setText( Math.cos(n)+"")    ;
       res2.setText("cos("+n+")");
    }//GEN-LAST:event_jButton68ActionPerformed

    private void jButton73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton73ActionPerformed
 double n=Double.parseDouble(res.getText());
       res1.setText( Math.tan(n)+"")    ;
       res2.setText("tan("+n+")");
    }//GEN-LAST:event_jButton73ActionPerformed

    private void jButton72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton72ActionPerformed
double n=Double.parseDouble(res.getText());
       res1.setText( Math.asin(n)+"")    ;    
       res2.setText("asin("+n+")");// TODO add your handling code here:
    }//GEN-LAST:event_jButton72ActionPerformed

    private void jButton70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton70ActionPerformed
      double n=Double.parseDouble(res.getText());
       res1.setText( Math.acos(n)+"")    ;
       res2.setText("acos("+n+")");
    }//GEN-LAST:event_jButton70ActionPerformed

    private void jButton69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton69ActionPerformed
       double n=Double.parseDouble(res.getText());
       res1.setText( Math.atan(n)+"")    ;
       res2.setText("atan("+n+")");
       
    }//GEN-LAST:event_jButton69ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
       double n=Double.parseDouble(res.getText());
     res2.setText("log("+n+")");
       res1.setText( Math.log(n)+"")    ;
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        double n=Double.parseDouble(res.getText());
        res2.setText("antilog("+n+")");
       res1.setText( Math.exp(n)+"")   ; 
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
      String n=JOptionPane.showInputDialog(this,"Specify the type(square,cube,rectangle etc..)\n you cn also use shortcuts(s,c,r,cd)");
      if("square".equals(n)||"s".equals(n)){
           double a=Double.parseDouble(JOptionPane.showInputDialog(this," specify length"));
           
           res2.setText("Area of square of length "+a);
           res1.setText(a*a+"");
      }
      else if("cube".equals(n)||"c".equals(n)){
           double a=Double.parseDouble(JOptionPane.showInputDialog(this," specify length"));
          
           
           res2.setText("Area of cube of length "+a);
           res1.setText(6*a*a+"");
      }
     else if("rectangle".equals(n)||"r".equals(n)){
           double a=Double.parseDouble(JOptionPane.showInputDialog(this," specify length"));
           double b=Double.parseDouble(JOptionPane.showInputDialog(this," specify width"));
          
           res2.setText("Area of rectangle of length "+a+",width "+b);
           res1.setText(a*b+"");
      }
     else if("cuboid".equals(n)||"cd".equals(n)){
           double a=Double.parseDouble(JOptionPane.showInputDialog(this," specify length"));
           double b=Double.parseDouble(JOptionPane.showInputDialog(this," specify width"));
           double h=Double.parseDouble(JOptionPane.showInputDialog(this," specify height"));
           
           res2.setText("Area of cuboid of length "+a+",width "+b+",height "+h);
           res1.setText(2*(a*b+b*h+h*a)+"");
      }
      
      else if("cylinder".equals(n)||"cd".equals(n)){
           double r=Double.parseDouble(JOptionPane.showInputDialog(this," specify radius"));
           
           double h=Double.parseDouble(JOptionPane.showInputDialog(this," specify height"));
          
           res2.setText("Area of cylinder of length "+r+",height "+h);
           res1.setText(2*Math.PI*r*(r+h)+"");
      }
      else if("circle".equals(n)||"cd".equals(n)){
           
           double r=Double.parseDouble(JOptionPane.showInputDialog(this," specify radius"));
           
           res2.setText("Area of circle of length "+r);
           res1.setText(Math.PI*(r*r)+"");
      }
      else if("trapezoid".equals(n)||"cd".equals(n)){
           double a=Double.parseDouble(JOptionPane.showInputDialog(this," specify base1"));
           double b=Double.parseDouble(JOptionPane.showInputDialog(this," specify base2"));
           double h=Double.parseDouble(JOptionPane.showInputDialog(this," specify height"));
         
           res2.setText("Area of trapezoid of base1 "+a+",base2 "+b+",height "+h);
           res1.setText(h/2*(a+b)+"");
      }
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton76ActionPerformed
       String n=JOptionPane.showInputDialog(this,"Specify the type(cone,cube,cylinder etc..)\n you cn also use shortcuts(s,c,r,cd)");
      if("ellipsoid".equals(n)||"s".equals(n)){
           double a=Double.parseDouble(JOptionPane.showInputDialog(this," specify radius1"));
           double b=Double.parseDouble(JOptionPane.showInputDialog(this," specify radius2"));
           double c=Double.parseDouble(JOptionPane.showInputDialog(this," specify radius3"));
        
           res2.setText("Area of ellipsoid of radi "+a+","+","+b+","+c);
           res1.setText(a*a+"");
      }
      else if("cube".equals(n)||"c".equals(n)){
           double a=Double.parseDouble(JOptionPane.showInputDialog(this," specify length"));
          
         
           res2.setText("volume of cube of length "+a);
           res1.setText(a*a*a+"");
      }
     else if("pyramid".equals(n)||"r".equals(n)){
           double a=Double.parseDouble(JOptionPane.showInputDialog(this," specify length"));
           double b=Double.parseDouble(JOptionPane.showInputDialog(this," specify height"));
          
           res2.setText("volume of pyraid of length "+a+",height "+b);
           res1.setText(a*b/3+"");
      }
     else if("cuboid".equals(n)||"cd".equals(n)){
           double a=Double.parseDouble(JOptionPane.showInputDialog(this," specify length"));
           double b=Double.parseDouble(JOptionPane.showInputDialog(this," specify width"));
           double h=Double.parseDouble(JOptionPane.showInputDialog(this," specify height"));
          
           res2.setText("Volume of cuboid of length "+a+",width "+b+",height "+h);
           res1.setText((a*b*h)+"");
      }
      
      else if("cylinder".equals(n)||"cd".equals(n)){
           double r=Double.parseDouble(JOptionPane.showInputDialog(this," specify radius"));
           
           double h=Double.parseDouble(JOptionPane.showInputDialog(this," specify height"));
         
           res2.setText("volume of cylinder of length "+r+",height "+h);
           res1.setText(Math.PI*r*r*(h)+"");
      }
      else if("sphere".equals(n)||"cd".equals(n)){
           
           double r=Double.parseDouble(JOptionPane.showInputDialog(this," specify radius"));
          
           res2.setText("volume of sphere of radius "+r);
           res1.setText(4*Math.PI*(r*r*r)/3+"");
      }
     else if("cone".equals(n)||"cd".equals(n)){
           double r=Double.parseDouble(JOptionPane.showInputDialog(this," specify radius"));
           
           double h=Double.parseDouble(JOptionPane.showInputDialog(this," specify height"));
         
           res2.setText("volume of cone of length "+r+",height "+h);
           res1.setText(Math.PI*r*r*(h)/3+"");
      }
    }//GEN-LAST:event_jButton76ActionPerformed

    private void jButton75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton75ActionPerformed
        double n=Double.parseDouble(res.getText());
        res1.setText(n/100+"");
        res2.setText("% of "+n);
    }//GEN-LAST:event_jButton75ActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dActionPerformed

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseDragged
        jButton1.setBackground(Color.red);
    }//GEN-LAST:event_jButton1MouseDragged

    private void b9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b9MouseEntered
         b9.setBackground(Color.getHSBColor(240, 240, 240));
    }//GEN-LAST:event_b9MouseEntered

    private void b9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b9MouseExited
         b9.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_b9MouseExited

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
jButton5.setBackground(Color.getHSBColor(240, 240, 240));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseEntered
     jButton11.setBackground(Color.getHSBColor(240, 240, 240)); 
    }//GEN-LAST:event_jButton11MouseEntered

    private void jButton15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseEntered
      jButton15.setBackground(Color.getHSBColor(240, 240, 240)); 
    }//GEN-LAST:event_jButton15MouseEntered

    private void jButton12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseEntered
      jButton12.setBackground(Color.getHSBColor(240, 240, 240));   // TODO add your handling code here:
    }//GEN-LAST:event_jButton12MouseEntered

    private void jButton14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseEntered
              jButton14.setBackground(Color.getHSBColor(240, 240, 240));   // TODO add your handling code here:

    }//GEN-LAST:event_jButton14MouseEntered

    private void jButton20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton20MouseEntered
jButton20.setBackground(Color.getHSBColor(240, 240, 240));         // TODO add your handling code here:
    }//GEN-LAST:event_jButton20MouseEntered

    private void jButton19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MouseEntered
jButton19.setBackground(Color.getHSBColor(240, 240, 240));         // TODO add your handling code here:
    }//GEN-LAST:event_jButton19MouseEntered

    private void jButton18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseEntered
jButton18.setBackground(Color.getHSBColor(240, 240, 240));         // TODO add your handling code here:
    }//GEN-LAST:event_jButton18MouseEntered

    private void jButton17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseEntered
jButton17.setBackground(Color.getHSBColor(240, 240, 240));         // TODO add your handling code here:
    }//GEN-LAST:event_jButton17MouseEntered

    private void jButton13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseEntered
jButton13.setBackground(Color.getHSBColor(240, 240, 240));         // TODO add your handling code here:
    }//GEN-LAST:event_jButton13MouseEntered

    private void jButton9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseEntered
jButton9.setBackground(Color.getHSBColor(240, 240, 240));         // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
 jButton5.setBackground(Color.LIGHT_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseExited
 jButton11.setBackground(Color.LIGHT_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11MouseExited

    private void jButton15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseExited
 jButton15.setBackground(Color.LIGHT_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15MouseExited

    private void jButton13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseExited
jButton13.setBackground(Color.LIGHT_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13MouseExited

    private void jButton9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseExited
jButton9.setBackground(Color.LIGHT_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseExited

    private void jButton17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseExited
jButton17.setBackground(Color.LIGHT_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17MouseExited

    private void jButton18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseExited
jButton18.setBackground(Color.LIGHT_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18MouseExited

    private void jButton19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MouseExited
jButton19.setBackground(Color.LIGHT_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19MouseExited

    private void jButton12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseExited
jButton12.setBackground(Color.LIGHT_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12MouseExited

    private void jButton14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseExited
jButton14.setBackground(Color.LIGHT_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14MouseExited

    private void jButton20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton20MouseExited
jButton20.setBackground(Color.LIGHT_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(samplevedi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(samplevedi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(samplevedi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(samplevedi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new samplevedi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton d;
    private javax.swing.JRadioButton g;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mem;
    private javax.swing.JLabel op;
    private javax.swing.JRadioButton r;
    private javax.swing.JTextArea res;
    private javax.swing.JTextField res1;
    private javax.swing.JTextArea res2;
    private javax.swing.JLabel x;
    private javax.swing.JLabel y;
    // End of variables declaration//GEN-END:variables
}
